In [2]:
import pandas as pd
Education = pd. read_csv('Education.csv')
Education

    Unnamed: 0                State1  Highschoold  Bachelord  Hillary   Donald
0            1                Alaska         64.1       27.5   116454   163387
1            2               Arizona         58.8       26.9  1161167  1252401
2            3              Arkansas         63.6       20.1   380494   684872
3            4            California         50.5       30.7  8753788  4483810
4            5              Colorado         53.2       37.0  1338870  1202484
5            6           Connecticut         52.7       36.5   897572   673215
6            7              Delaware         58.8       28.9   235603   185127
7            8  District Of Columbia         36.0       52.4   282830    12723
8            9               Florida         59.7       26.4  4504975  4617886
9           10               Georgia         56.7       28.0  1877963  2089104
10          11                Hawaii         60.3       30.1   266891   128847
11          12                 Idaho         63.7       25.1   189765   409055
12          13              Illinois         55.9       31.4  3090729  2146015
13          14               Indiana         64.0       23.2  1033126  1557286
14          15                  Iowa         65.3       25.7   653669   800983
15          16                Kansas         59.5       30.3   427005   671018
16          17              Kentucky         61.5       21.5   628854  1202971
17          18             Louisiana         60.8       21.8   780154  1178638
18          19                 Maine         63.2       27.9   357735   335593
19          20              Maryland         51.9       36.8  1677928   943169
20          21         Massachusetts         50.0       39.4  1995196  1090893
21          22              Michigan         63.0       25.9  2268839  2279543
22          23             Minnesota         59.5       32.6  1367716  1322951
23          24           Mississippi         61.4       20.1   485131   700714
24          25              Missouri         61.4       26.2  1071068  1594511
25          26               Montana         63.4       28.7   177709   279240
26          27              Nebraska         62.0       28.5   284494   495961
27          28                Nevada         62.2       22.4   539260   512058
28          29         New Hampshire         58.1       33.7   348526   345790
29          30            New Jersey         52.3       35.8  2148278  1601933
30          31            New Mexico         57.8       25.8   385234   319667
31          32              New York         52.0       33.2  4556124  2819534
32          33        North Carolina         57.6       27.3  2189316  2362631
33          34          North Dakota         63.7       27.2    93758   216794
34          35                  Ohio         63.3       25.2  2394164  2841005
35          36              Oklahoma         62.9       23.5   420375   949136
36          37                Oregon         59.7       29.7  1002106   782403
37          38          Pennsylvania         61.2       27.5  2926441  2970733
38          39          Rhode Island         53.9       31.3   252525   180543
39          40        South Carolina         59.4       25.1   855373  1155389
40          41          South Dakota         64.2       26.2   117458   227721
41          42             Tennessee         60.6       23.8   870695  1522925
42          43                 Texas         54.5       26.7  3877868  4685047
43          44                  Utah         60.6       30.3   310676   515231
44          45               Vermont         56.6       34.8   178573    95369
45          46              Virginia         52.3       35.2  1981473  1769443
46          47            Washington         58.1       31.9  1742718  1221747
47          48         West Virginia         65.6       18.3   188794   489371
48          49             Wisconsin         63.6       26.8  1382536  1405284
49          50               Wyoming         67.7       24.7    55973   174419

In [8]:
import statsmodels.api as sm

Y = Education['Hillary']
X = Education[['Highschoold', 'Bachelord']]
model = sm.OLS(Y,X).fit()

print (model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Hillary   R-squared:                       0.426
Model:                            OLS   Adj. R-squared:                  0.402
Method:                 Least Squares   F-statistic:                     17.78
Date:                Mon, 30 Apr 2018   Prob (F-statistic):           1.67e-06
Time:                        14:03:04   Log-Likelihood:                -783.06
No. Observations:                  50   AIC:                             1570.
Df Residuals:                      48   BIC:                             1574.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Highschoold -4266.3848   1.34e+04     -0.318      0.752   -3.13e+04    2.27e+04
Bachelord    5.322e+04   2.71e+04      1.961      0.056   -1340.136    1.08e+05
==============================================================================
Omnibus:                       47.653   Durbin-Watson:                   2.223
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              205.399
Skew:                           2.514   Prob(JB):                     2.50e-45
Kurtosis:                      11.563   Cond. No.                         8.93
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [10]:
import statsmodels.api as sm

Y = Education['Donald']
X = Education[['Highschoold', 'Bachelord']]
model = sm.OLS(Y,X).fit()

print (model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 Donald   R-squared:                       0.522
Model:                            OLS   Adj. R-squared:                  0.502
Method:                 Least Squares   F-statistic:                     26.16
Date:                Mon, 30 Apr 2018   Prob (F-statistic):           2.07e-08
Time:                        14:03:38   Log-Likelihood:                -769.27
No. Observations:                  50   AIC:                             1543.
Df Residuals:                      48   BIC:                             1546.
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Highschoold  1.384e+04   1.02e+04      1.358      0.181   -6648.786    3.43e+04
Bachelord    1.383e+04   2.06e+04      0.671      0.505   -2.76e+04    5.52e+04
==============================================================================
Omnibus:                       21.139   Durbin-Watson:                   2.190
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.411
Skew:                           1.532   Prob(JB):                     6.77e-07
Kurtosis:                       5.061   Cond. No.                         8.93
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.